# Generated by Django 3.2.5 on 2021-07-31 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main Title of the Course', max_length=100, verbose_name='Course Title')),
                ('short_description', models.CharField(help_text='Short Description of the course', max_length=250, verbose_name='Course Description')),
                ('image', models.ImageField(help_text='Course Image', upload_to='courses', verbose_name='Upload Image')),
                ('price', models.PositiveIntegerField(help_text='What is the price of the course', verbose_name='Price')),
                ('idx', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
