# Generated by Django 3.2.5 on 2021-07-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Max characters allowed 100', max_length=100, verbose_name='Heading')),
            ],
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='short_description',
            field=models.CharField(help_text='Short Description of the course (Max characters allowed 250)', max_length=250, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='title',
            field=models.CharField(help_text='Main Title of the Course', max_length=100, verbose_name='Course Title (Max characters allowed 100)'),
        ),
        migrations.CreateModel(
            name='CourseSubHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(help_text='Max characters allowed 100', max_length=100, verbose_name=' Sub Heading')),
                ('duration', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('display', models.BooleanField(default=False, help_text='Click on checkbox if you wish to display recording to unauthorized user', verbose_name='Display Recording')),
                ('headings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.courseheadings', verbose_name='Course Heading')),
            ],
        ),
        migrations.AddField(
            model_name='courseheadings',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.coursedescription', verbose_name='Course'),
        ),
    ]
