# Generated by Django 3.2.5 on 2021-07-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_auto_20210731_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubHeading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_heading', models.CharField(help_text='Max characters allowed 100', max_length=100, verbose_name=' Sub Heading')),
                ('duration', models.CharField(help_text='Duration of the recording', max_length=10, verbose_name='Duration')),
                ('url', models.URLField()),
                ('display', models.BooleanField(default=False, help_text='Click on checkbox if you wish to display recording to unauthorized user', verbose_name='Display Recording')),
            ],
        ),
        migrations.AlterField(
            model_name='coursedescription',
            name='title',
            field=models.CharField(help_text='Main Title of the Course  (Max characters allowed 100)', max_length=100, verbose_name='Course Title'),
        ),
        migrations.RenameModel(
            old_name='CourseHeadings',
            new_name='CourseHeading',
        ),
        migrations.DeleteModel(
            name='CourseSubHeadings',
        ),
        migrations.AddField(
            model_name='coursesubheading',
            name='headings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.courseheading', verbose_name='Course Heading'),
        ),
    ]
