# Generated by Django 3.2.5 on 2021-08-02 05:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_coursesubheading_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedescription',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
