# Generated by Django 3.2.5 on 2021-08-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_coursedescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubheading',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
