# Generated by Django 3.2.5 on 2021-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='resp',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('failed', 'Failed'), ('success', 'Success')], max_length=7),
        ),
    ]
