# Generated by Django 3.2.5 on 2021-09-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20210910_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='checkout_resp',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
